### PR TITLE
Cleaned the untidy mess in setup.py

### PR DESCRIPTION
**Pull request by KOLANICH**
Fixes: #20

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@KOLANICH where's the version set?

**Comment by KOLANICH** [comment]
The latest git tag on the branch is a version. It should look like a version.

**Comment by Conan-Kudo** [comment]
@KOLANICH The version needs to be correctly propagated into the code, as it's used in a couple of places there.

**Comment by KOLANICH** [comment]
>The version needs to be correctly propagated into the code

It is possible to parse it from the metadata using `pkg_resources`.

>Also, how will this work if someone uses a github archive?

No, since it is taken from git. If an archive doesn't contain whole git repo with `.git` dir, or if there is no git in the system where build is done, it will fail hard. Though IMHO it is not an issue: git is present in all devs machines today.

**Comment by Conan-Kudo** [comment]
Mandating `git` as a build dependency is not acceptable. Sorry. That said, I do have an alternative fix that I can push.

**Pull request closed without merging**
