### PR TITLE
Python3 compatibility

### PR DESCRIPTION
**Pull request by keszybz**
This is an updated variant of #8. I tried to reuse as much as possible from the original PR, but some things are done differently:
- the `2to3` fixers are applied separately, so it's easier to see what is going on
- stylistic fixes are not done, except when I'm rewriting some line of code by hand anyway
- no tests fail
- the changes that directly affect python2 code are localized near the end. Patches until "Add b'' markers in various places" inclusive should have no visible changes in behaviour under python2, so debugging any regressions should be easier.

Note that patches are not in chronological order, so github will reorder them.

Test output (the same under python2 and 3):
```
URLGRABBER_EXT_DOWN=scripts/urlgrabber-ext-down PYTHONPATH=. python3 test/runtests.py
urlgrabber tests
  test_grabber
    BaseProxyTests
    Test checkfunc behavior
      check for proper args when used with urlgrab                    ... ok
      check failure with urlgrab checkfunc                            ... ok
      check success with urlgrab checkfunc                            ... ok
      check for proper args when used with urlread                    ... ok
      check failure with urlread checkfunc                            ... ok
      check success with urlread checkfunc                            ... ok
    CommonRegetTests
      exception raised for illegal reget mode                         ... ok
    FTPRegetTests
      simple (forced) reget                                           ... skip
    Test failure behavior
      failure callback is called with the proper args                 ... ok
      failure callback is called on retry                             ... ok
    FileObjectTests
      PYCurlFileObject .read() method                                 ... ok
      PyCurlFileObject .readline() method                             ... ok
      PyCurlFileObject .readlines() method                            ... ok
      PyCurlFileObject .read(N) with small N                          ... ok
    FileRegetTests
      simple (forced) reget                                           ... ok
      test_newer_check_timestamp (test_grabber.FileRegetTests)        ... skip
      test_older_check_timestamp (test_grabber.FileRegetTests)        ... skip
    HTTPRegetTests
      simple (forced) reget                                           ... ok
      test_newer_check_timestamp (test_grabber.HTTPRegetTests)        ... skip
      test_older_check_timestamp (test_grabber.HTTPRegetTests)        ... skip
    HTTPTests
      do an HTTP post                                                 ... ok
      download reference file via HTTP                                ... ok
    Test interrupt callback behavior
      interrupt callback is called on retry                           ... ok
      interrupt callback raises an exception                          ... ok
    ProFTPDSucksTests
      test_restart_workaround (test_grabber.ProFTPDSucksTests)        ... skip
    ProxyFTPAuthTests
      test_bad_password (test_grabber.ProxyFTPAuthTests)              ... skip
      test_good_password (test_grabber.ProxyFTPAuthTests)             ... skip
    ProxyHTTPAuthTests
      test_bad_password (test_grabber.ProxyHTTPAuthTests)             ... skip
      test_good_password (test_grabber.ProxyHTTPAuthTests)            ... skip
    Test module level functions defined in grabber.py
      module-level urlgrab() function                                 ... ok
      module-level urlopen() function                                 ... ok
      module-level urlread() function                                 ... ok
    Test grabber.URLGrabber class
      grabber.URLGrabber.__init__() **kwargs handling.                ... ok
      grabber.URLGrabber._make_callback() tests                       ... ok
    URLParserTestCase
      grabber.URLParser.parse() with opts.prefix                      ... ok
      test url parsing common to all OSs                              ... ok
      test url parsing on windows systems                             ... skip
      test url parsing on posix systems                               ... ok
  test_byterange
    Test module level functions defined in range.py
      byterange.range_header_to_tuple()                               ... ok
      byterange.range_tuple_normalize()                               ... ok
      byterange.range_tuple_to_header()                               ... ok
    Test range.RangeableFileObject class
      RangeableFileObject.read()                                      ... ok
      RangeableFileObject.read(): to end of file.                     ... ok
      RangeableFileObject.readline()                                  ... ok
      RangeableFileObject.seek()                                      ... ok
      RangeableFileObject.tell()                                      ... ok
  mirror.py tests
    ActionTests
      test the effects of a callback-returned action                  ... ok
      test default action policy                                      ... ok
      test the effects of passed-in default_action                    ... ok
      test the effects of method-level default_action                 ... ok
    BadMirrorTests
      test that a bad mirror raises URLGrabError                      ... ok
    BasicTests
      MirrorGroup.urlgrab                                             ... ok
      MirrorGroup.urlopen                                             ... ok
      MirrorGroup.urlread                                             ... ok
    CallbackTests
      test that the callback can correctly re-raise the exception     ... ok
      test that MG executes the failure callback correctly            ... ok
    FailoverTests
      test that a the MG fails over past a bad mirror                 ... ok
    HttpReplyCode
      tests the propagation of HTTP reply code                        ... ok
      test client-side processing of HTTP ranges                      ... ok
      test bypassing proxy cache on failure                           ... ok
    SubclassTests
      MGRandomOrder.urlgrab                                           ... ok
      MGRandomStart.urlgrab                                           ... ok

-------------------------------------------------------------------------------
Ran 62 tests in 3.714s

OK (skipped=11)
```
So the FTP and proxy tests are all skipped. It would be nice to create a setup to allow them to run, but I didn't do that.

It is quite possible that things which are not covered by tests don't work properly, especially under python3. If you can show some examples of things which don't work, I'd be happy to fix them.

### CODE REVIEW

**Comment by keszybz** [comment]
One of the patches is the same as #6. I should adjust authorship probably.

**Comment by Conan-Kudo** [comment]
@keszybz That's probably a good idea.

**Comment by Conan-Kudo** [comment]
@keszybz Do you intend to adjust authorship or is this good to go?

**Comment by keszybz** [comment]
Updated:
- one of the commits is replaced with patch from #6 + a small refactoring patch right afterwards
- three cleanup patches added at the very end:
  - Replace some type() with specific class names 
  - Drop some unnecessary continuation backslashes
  - tests: do not exit with "success" on error

This is good to go from my side. More testing would of course be great.

**Comment by Conan-Kudo** [comment]
Merged, thanks!

**Comment by brejoc** [comment]
@keszybz Thanks a bunch for taking this into your hand!

**Pull request merged**
